version = 1

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/mpenning/ciscoconfparse"
  dependencies_vendored = false

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"
