---
# This yaml requires a specific python package -> https://pre-commit.com/
#    make sure your virtualenv has the pre-commit pypi dependency...
#
# To install this hook config in .git/hooks/pre-commit:
# - pre-commit install
# - pre-commit run --all-files
#
# Manually run all pre-commit checks with:
#    `pre-commit run --all-files`
repos:

  # github.com/pallets/flask uses this plugin... auto-format code for
  # the --pyXXXXXXX argument.
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.31.0
    hooks:
      - id: pyupgrade
        args: ["--py3-plus"]

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0  # Use the ref you want to point at
    hooks:
    - id: python-no-eval
    - id: rst-backticks

  - repo: https://github.com/asottile/add-trailing-comma
    rev: v2.2.1
    hooks:
    -   id: add-trailing-comma  # Add a trailing comma in kwarg params

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    - id: check-yaml
    - id: check-json
    - id: check-symlinks                        # Look for isolated symlinks
    - id: check-shebang-scripts-are-executable  # Fix permissions on scripts
    - id: check-docstring-first # Forbid code before a function's docstring
    - id: end-of-file-fixer
    - id: debug-statements
    - id: requirements-txt-fixer
    - id: fix-byte-order-marker
    - id: fix-encoding-pragma   # Add "# -*- coding: utf-8 -*-" to top of file
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: no-commit-to-branch   # By default, protect 'master' and 'main'
