[build-system]
requires = ["poetry>=1.2.2", "poetry-core>=1.3.2", "wheel>=0.37.0", "packaging>=21.0"]
build-backend = "poetry.core.masonry.api"
requires-python = ">=3.7.0"

##############################################################################
#
# IMPORTANT:
# pyproject.toml has several different formats (such as a [project] section);
# however, pip will NOT install unless I base pyproject.toml on the
# [tool.poetry] section below.
#
# Maybe it's my fault, but I have not had success trying to migrate to 
# a [project] section with pip installs.  I have stopped trying because
# the problem is too complicated to continue throwing cycles at making a
# [project] section work with 'pip install ciscoconfparse'.
#
##############################################################################
#[project]

[tool.poetry]
name = "ciscoconfparse"
version = "1.6.53"
description = "Parse, Audit, Query, Build, and Modify Cisco IOS-style and JunOS-style configurations"
license = "GPL-3.0-only"
authors = ["Mike Pennington <mike@pennington.net>"]
readme = "README.md"
keywords = ["Parse", "audit", "query", "modify", "Cisco IOS", "Cisco", "NXOS", "ASA", "Juniper"]
classifiers=[
    "Development Status :: 5 - Production/Stable",
    "Environment :: Plugins",
    "Intended Audience :: Developers",
    "Intended Audience :: System Administrators",
    "Intended Audience :: Information Technology",
    "Intended Audience :: Telecommunications Industry",
    "License :: OSI Approved :: GNU General Public License (GPL)",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Topic :: Communications",
    "Topic :: Internet",
    "Topic :: System :: Networking",
    "Topic :: System :: Networking :: Monitoring",
]
include = [
    "CHANGES.md",
    "CONTRIBUTING.md",
    "LICENSE",
    "Makefile",
    "README_git_workflow.md"
]
exclude = [
    "coverage.json"
]

[tool.poetry.dependencies]
passlib = "^1.7.4"
dnspython = "^2.1.0"
loguru = "0.6.0"
toml = ">=0.10.2"

[tool.poetry.urls]
source = "https://github.com/mpenning/ciscoconfparse"
homepage = "http://www.pennington.net/py/ciscoconfparse/"
repository = "https://github.com/mpenning/ciscoconfparse"
documentation = "http://www.pennington.net/py/ciscoconfparse/"

[tool.poetry.dev-dependencies]
pytest = "6.2.5"
pre-commit = "2.20.0"
#black = ">=20.8b1"
#fabric = "2.6.0"
#Sphinx = "^4.3.0"
#sphinx-bootstrap-theme = "^0.8.0"
