---
blank_issues_enabled: false
contact_links:
  - name: Security issue
    url: penningtonthing@gmail.com
    about: Do not report security issues publicly. Email our security contact.
  - name: Questions
    url: https://stackoverflow.com/questions/tagged/ciscoconfparse
    about: Search for and ask questions about your code on Stack Overflow.
