name: github-actions-run-ciscoconfparse-unit-tests
on: push

# https://www.jeffgeerling.com/blog/2020/travis-cis-new-pricing-plan-threw-wrench-my-open-source-works
jobs:
  run-ccp-unit-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: "checkout the latest push"
        uses: actions/checkout@v2

      # Setup Python (faster than using Python container)
      - name: "Setup Python"
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: "Install poetry"
        run: |
          "pip install -q poetry"

      - name: "Install dependencies"
        run: |
          "poetry install"

      - name: "Install latest versions of the dependencies"
        run: |
          "poetry update passlib==1.7.4"
          "poetry update dnspython==2.1.0"
          "poetry update loguru==0.5.3"
          "poetry update toml==0.10.2"
          "poetry update ipaddr>=2.1.11"

      - name: Run make test
        run: |
          "make test"

#      - uses: actions/setup-node@v2
#        with:
#          node-version: '14'
#      - run: npm install -g bats
#      - run: bats -v
